name       : ospray
version    : 2.8.0
release    : 2
source     :
    - https://github.com/ospray/ospray/archive/refs/tags/v2.8.0.tar.gz : 2dabc75446a0e2e970952d325f930853a51a9b4d1868c8135f05552a4ae04d39
homepage   : https://www.ospray.org/
license    : Apache-2.0
component  : programming.library
summary    : Open, Scalable, and Portable Ray Tracing Engine
description: |
    Intel OSPRay is an open source, scalable, and portable ray tracing engine for high-performance, high-fidelity visualization on CPUs.
builddeps  :
    - ispc
    - openimagedenoise-devel
    - openvkl-devel
    - snappy-devel
rundeps    :
    - devel :
        - openimagedenoise-devel
        - openvkl-devel
        - snappy-devel
setup      : |
    %cmake_ninja \
        -DOSPRAY_APPS_BENCHMARK=OFF \
        -DOSPRAY_APPS_TESTING=OFF \
        -DOSPRAY_APPS_TUTORIALS=OFF \
        -DOSPRAY_APPS_EXAMPLES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share
